//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "IContactMgrExt.h"
#import "IGroupMgrExt.h"
#import "MMMessageCellViewDelegate.h"
#import "MMMutipleSelectDataSourceDelegate.h"
#import "MMNetExt.h"
#import "MMPreviewPanelDataSource.h"
#import "MMPreviewPanelDelegate.h"
#import "MMTableViewDelegate.h"
#import "MMViewerWindowDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"
#import "QLPreviewPanelDataSource.h"
#import "QLPreviewPanelDelegate.h"
#import "VoipMessageCellViewDelegate.h"

@class MMChatInfoView, MMChatInspector, MMChatMessageDataSource, MMChatsBannerCellView, MMMessageCellView, MMMessageScrollView, MMMessageTableItem, MMMessageUnreadTipsButton, MMPreviewPanel, MMTableView, MMTimer, NSClipView, NSString, NSView, WCContactData;

@interface MMChatMessageViewController : NSViewController <NSTableViewDataSource, NSTableViewDelegate, MMTableViewDelegate, MMMessageCellViewDelegate, MMViewerWindowDelegate, IContactMgrExt, IGroupMgrExt, QLPreviewPanelDelegate, QLPreviewPanelDataSource, MMPreviewPanelDelegate, MMPreviewPanelDataSource, MMNetExt, VoipMessageCellViewDelegate, MMMutipleSelectDataSourceDelegate>
{
    double _reloadStartedTime;
    BOOL _isSettingChatContact;
    BOOL _onTrackingMouseMoveOnChatBoard;
    BOOL _hasSelectedChat;
    BOOL _isNoNetwork;
    BOOL _isLoadingHistory;
    BOOL _isPerformingAutoScrollToBottom;
    BOOL _isLastMsgUnreadTipsShouldShownOnTop;
    BOOL _hasUnreadMsgsBeforeSetChatContact;
    BOOL _hasScrollToBottomAfterSetChatContact;
    unsigned int _lastCurUserActiveTime;
    MMChatInfoView *_chatInfoView;
    CDUnknownBlockType _viewDidLoadBlock;
    CDUnknownBlockType _brandChatNameClickBlock;
    WCContactData *_chatContact;
    id <MMComposeInputViewDelegate> _composeInputViewDelegate;
    id <MMChatMemberListViewDelegate> _chatMemberListViewDelegate;
    NSView *_chatMessageListView;
    MMMessageScrollView *_messageScrollView;
    MMTableView *_messageTableView;
    MMMessageUnreadTipsButton *_unreadTipsButton;
    MMChatInspector *_chatInspector;
    MMPreviewPanel *_mmPreviewPanel;
    MMMessageCellView *_currentMessageCellView;
    MMChatsBannerCellView *_bannerCellView;
    NSClipView *_stageClipView;
    MMChatMessageDataSource *_messageDataSource;
    MMMessageTableItem *_curPreviewItem;
    MMMessageTableItem *_currentPreviewItem;
    MMMessageTableItem *_seletedMessageTableItem;
    MMTimer *_netStatusTimer;
    MMTimer *_scrollDelaytimer;
    id _userActiveEvent;
    unsigned long long _lastSetChatContactTimeInMs;
}

@property(nonatomic) BOOL hasScrollToBottomAfterSetChatContact; // @synthesize hasScrollToBottomAfterSetChatContact=_hasScrollToBottomAfterSetChatContact;
@property(nonatomic) BOOL hasUnreadMsgsBeforeSetChatContact; // @synthesize hasUnreadMsgsBeforeSetChatContact=_hasUnreadMsgsBeforeSetChatContact;
@property(nonatomic) unsigned long long lastSetChatContactTimeInMs; // @synthesize lastSetChatContactTimeInMs=_lastSetChatContactTimeInMs;
@property(nonatomic) BOOL isLastMsgUnreadTipsShouldShownOnTop; // @synthesize isLastMsgUnreadTipsShouldShownOnTop=_isLastMsgUnreadTipsShouldShownOnTop;
@property(nonatomic) unsigned int lastCurUserActiveTime; // @synthesize lastCurUserActiveTime=_lastCurUserActiveTime;
@property BOOL isPerformingAutoScrollToBottom; // @synthesize isPerformingAutoScrollToBottom=_isPerformingAutoScrollToBottom;
@property(retain, nonatomic) id userActiveEvent; // @synthesize userActiveEvent=_userActiveEvent;
@property BOOL isLoadingHistory; // @synthesize isLoadingHistory=_isLoadingHistory;
@property(retain, nonatomic) MMTimer *scrollDelaytimer; // @synthesize scrollDelaytimer=_scrollDelaytimer;
@property(nonatomic) BOOL isNoNetwork; // @synthesize isNoNetwork=_isNoNetwork;
@property(retain, nonatomic) MMTimer *netStatusTimer; // @synthesize netStatusTimer=_netStatusTimer;
@property(retain, nonatomic) MMMessageTableItem *seletedMessageTableItem; // @synthesize seletedMessageTableItem=_seletedMessageTableItem;
@property(retain, nonatomic) MMMessageTableItem *currentPreviewItem; // @synthesize currentPreviewItem=_currentPreviewItem;
@property(retain, nonatomic) MMMessageTableItem *curPreviewItem; // @synthesize curPreviewItem=_curPreviewItem;
@property(retain, nonatomic) MMChatMessageDataSource *messageDataSource; // @synthesize messageDataSource=_messageDataSource;
@property(nonatomic) __weak NSClipView *stageClipView; // @synthesize stageClipView=_stageClipView;
@property(retain, nonatomic) MMChatsBannerCellView *bannerCellView; // @synthesize bannerCellView=_bannerCellView;
@property(retain, nonatomic) MMMessageCellView *currentMessageCellView; // @synthesize currentMessageCellView=_currentMessageCellView;
@property(retain, nonatomic) MMPreviewPanel *mmPreviewPanel; // @synthesize mmPreviewPanel=_mmPreviewPanel;
@property(retain, nonatomic) MMChatInspector *chatInspector; // @synthesize chatInspector=_chatInspector;
@property(retain, nonatomic) MMMessageUnreadTipsButton *unreadTipsButton; // @synthesize unreadTipsButton=_unreadTipsButton;
@property(nonatomic) __weak MMTableView *messageTableView; // @synthesize messageTableView=_messageTableView;
@property(nonatomic) __weak MMMessageScrollView *messageScrollView; // @synthesize messageScrollView=_messageScrollView;
@property(nonatomic) __weak NSView *chatMessageListView; // @synthesize chatMessageListView=_chatMessageListView;
@property(nonatomic) __weak id <MMChatMemberListViewDelegate> chatMemberListViewDelegate; // @synthesize chatMemberListViewDelegate=_chatMemberListViewDelegate;
@property(nonatomic) __weak id <MMComposeInputViewDelegate> composeInputViewDelegate; // @synthesize composeInputViewDelegate=_composeInputViewDelegate;
@property(nonatomic) BOOL hasSelectedChat; // @synthesize hasSelectedChat=_hasSelectedChat;
@property(retain, nonatomic) WCContactData *chatContact; // @synthesize chatContact=_chatContact;
@property(copy, nonatomic) CDUnknownBlockType brandChatNameClickBlock; // @synthesize brandChatNameClickBlock=_brandChatNameClickBlock;
@property(copy, nonatomic) CDUnknownBlockType viewDidLoadBlock; // @synthesize viewDidLoadBlock=_viewDidLoadBlock;
@property(nonatomic) __weak MMChatInfoView *chatInfoView; // @synthesize chatInfoView=_chatInfoView;
- (void).cxx_destruct;
- (BOOL)_isApplicationActive;
- (void)ensurePreviewPanelClose;
- (BOOL)shouldShowGroupChatNickName;
- (id)getNextVoiceMsgToPlay:(unsigned int)arg1;
- (long long)getVisibleUnreadMessageCount;
- (void)checkFirstUnreadMessageShown;
- (void)updateAllGroupMemberIfNeeded;
- (void)updateChatContactIfNeeded;
- (void)showNetworkBanner;
- (void)clearNetstatusTimer;
- (void)onNetStatusChange:(int)arg1;
- (BOOL)validateProposedFirstResponder:(id)arg1 forEvent:(id)arg2;
- (id)title;
- (void)loadMoreChatHistory;
- (void)doScrollViewBoundsDidChanged;
- (void)onScrollViewBoundsDidChanged:(id)arg1;
- (void)_recalculateAllHeights;
- (void)onNewWindowFrame:(id)arg1;
- (void)onUserActive;
- (void)onClickSession;
- (void)showChatDetailPanel:(id)arg1;
- (void)showChatInspector:(id)arg1;
- (void)OnChangeMemberShowDisplayName:(id)arg1;
- (void)onModifyContacts:(id)arg1;
- (void)unreadTipsDidClicked;
- (void)scrollToFirstUnReadMessagesIterally:(unsigned long long)arg1;
- (BOOL)scrollToFirstUnReadMessages:(unsigned long long)arg1;
- (void)showUnreadTipsIfNeededAnimated:(BOOL)arg1 isShowOnTop:(BOOL)arg2 scene:(int)arg3;
- (BOOL)isUnreadTipsShownOnBottom;
- (BOOL)isUnreadTipsShownOnTop;
- (BOOL)isUnreadTipsShown;
- (unsigned int)unreadCount;
- (struct CGRect)originScreenRectForAnimationForWindow:(id)arg1;
- (void)windowDidColsed:(id)arg1;
- (void)previewPanelDidClose:(id)arg1;
- (struct CGRect)previewPanel:(id)arg1 sourceFrameOnScreenForPreviewItem:(id)arg2;
- (id)previewPanel:(id)arg1 previewItemAtIndex:(long long)arg2;
- (unsigned int)getImgIndexInMessageList:(id)arg1;
- (unsigned int)getCurrPreviewImgIndex;
- (id)filterImgMsgDataList;
- (id)previewPanel:(id)arg1 shareContentAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewPanel:(id)arg1;
- (double)messageCellViewNeedsContainerWidth;
- (void)messageCellView:(id)arg1 didClickOnAvatarWithItem:(id)arg2;
- (void)messageCellView:(id)arg1 didDoubleClickOnAvatarWithItem:(id)arg2;
- (void)messageCellView:(id)arg1 needreload:(id)arg2;
- (void)forwardMessage:(id)arg1 toContacts:(id)arg2;
- (void)messageCellViewDidStartForwardMessageCommand:(id)arg1;
- (void)messageCellView:(id)arg1 gotMisdirectedKeyDown:(id)arg2;
- (void)messageCellViewNeedsReload:(id)arg1;
- (void)messageCellViewNeedsHeightRecalculated:(id)arg1;
- (void)messageCellView:(id)arg1 didUpdatePreviewContentWithItem:(id)arg2;
- (void)messageCellView:(id)arg1 showDetailWindowWithItem:(id)arg2;
- (id)makeCellViewWithMessage:(id)arg1;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)getChosenMessageList;
- (void)playEasterEggAnimationIfNeededWithMessages:(id)arg1;
- (void)setChatInfoViewStyle:(unsigned long long)arg1;
- (void)focusOnChatNameLabel;
- (void)loadMoreChatHistoryWithoutChangePosition;
- (void)adjustVisableHeightForResize;
- (void)layoutForResize;
- (void)setupUnreadTipsButton;
- (void)setupChatInfoView;
- (void)setCellViewToChoosable:(BOOL)arg1;
- (void)setupTableView;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

