//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "IContactMgrExt.h"
#import "MMComposeInputViewDelegate.h"
#import "MMNetExt.h"
#import "VoipMessageCellViewDelegate.h"

@class MMComposeTextView, MMView, NSButton, NSScrollView, NSString, NSTextField, NSView, WCContactData;

@interface MMComposeInputViewController : NSViewController <MMNetExt, IContactMgrExt, VoipMessageCellViewDelegate, MMComposeInputViewDelegate>
{
    BOOL isNoNetwork;
    MMComposeTextView *_composeTextView;
    id <MMComposeTextViewDelegate> _composeTextViewDelegate;
    WCContactData *_currnetChatContact;
    CDUnknownBlockType _viewDidLoadBlock;
    id <MMChatDetailSplitViewPositionInterface><MMChatMemberListViewDelegate><MMAnimateVoipTipsDelegate> _delegate;
    id <MMMutipleSelectDataSourceDelegate> _dataSourceDelegate;
    id <MMMutiplySelectAnimationDelegate> _mutiplySelectAnimationDelegate;
    NSView *_toolBarView;
    NSButton *_stickerButton;
    NSButton *_attachmentButton;
    NSButton *_screenShotButton;
    NSButton *_videoButton;
    NSButton *_voiceButton;
    NSScrollView *_messageInputView;
    MMView *_multipleSelectView;
    NSView *_multipleButtonContainer;
    NSTextField *_forwardLabel;
    NSTextField *_mergeForwardLabel;
    NSTextField *_addFavoritesLabel;
    NSTextField *_deleteLabel;
}

@property __weak NSTextField *deleteLabel; // @synthesize deleteLabel=_deleteLabel;
@property __weak NSTextField *addFavoritesLabel; // @synthesize addFavoritesLabel=_addFavoritesLabel;
@property __weak NSTextField *mergeForwardLabel; // @synthesize mergeForwardLabel=_mergeForwardLabel;
@property __weak NSTextField *forwardLabel; // @synthesize forwardLabel=_forwardLabel;
@property __weak NSView *multipleButtonContainer; // @synthesize multipleButtonContainer=_multipleButtonContainer;
@property __weak MMView *multipleSelectView; // @synthesize multipleSelectView=_multipleSelectView;
@property(nonatomic) __weak NSScrollView *messageInputView; // @synthesize messageInputView=_messageInputView;
@property(nonatomic) __weak NSButton *voiceButton; // @synthesize voiceButton=_voiceButton;
@property(nonatomic) __weak NSButton *videoButton; // @synthesize videoButton=_videoButton;
@property(nonatomic) __weak NSButton *screenShotButton; // @synthesize screenShotButton=_screenShotButton;
@property(nonatomic) __weak NSButton *attachmentButton; // @synthesize attachmentButton=_attachmentButton;
@property(nonatomic) __weak NSButton *stickerButton; // @synthesize stickerButton=_stickerButton;
@property(nonatomic) __weak NSView *toolBarView; // @synthesize toolBarView=_toolBarView;
@property(nonatomic) __weak id <MMMutiplySelectAnimationDelegate> mutiplySelectAnimationDelegate; // @synthesize mutiplySelectAnimationDelegate=_mutiplySelectAnimationDelegate;
@property(nonatomic) __weak id <MMMutipleSelectDataSourceDelegate> dataSourceDelegate; // @synthesize dataSourceDelegate=_dataSourceDelegate;
@property(nonatomic) __weak id <MMChatDetailSplitViewPositionInterface><MMChatMemberListViewDelegate><MMAnimateVoipTipsDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType viewDidLoadBlock; // @synthesize viewDidLoadBlock=_viewDidLoadBlock;
@property(retain, nonatomic) WCContactData *currnetChatContact; // @synthesize currnetChatContact=_currnetChatContact;
@property(nonatomic) __weak id <MMComposeTextViewDelegate> composeTextViewDelegate; // @synthesize composeTextViewDelegate=_composeTextViewDelegate;
@property(retain, nonatomic) MMComposeTextView *composeTextView; // @synthesize composeTextView=_composeTextView;
- (void).cxx_destruct;
- (id)_filterAllowFavItem:(id)arg1;
- (id)_filterAllowMergeForward:(id)arg1;
- (id)_filterAllowForward:(id)arg1;
- (id)_filterUndowloadMessage:(id)arg1;
- (void)AddFavoritesWithMultipleMsgList:(id)arg1;
- (void)ForwardWithMultipleMsgList:(id)arg1 toContacts:(id)arg2;
- (void)SendOneByOneWithMultipleSelectMsgList:(id)arg1 toCtontacts:(id)arg2;
- (void)SendWithMultipleSelectMsgList:(id)arg1 toContacts:(id)arg2;
- (void)ForwardMutipleSelect:(BOOL)arg1;
- (unsigned int)videoDuration:(id)arg1;
- (void)sendVideoMessageWithFileUrl:(id)arg1;
- (void)sendImageMessageWithImageData:(id)arg1 imageInfo:(id)arg2;
- (void)sendImageMessageWithImage:(id)arg1;
- (void)sendImageMessageWithFileUrl:(id)arg1;
- (void)sendFileWithFilePath:(id)arg1 fileName:(id)arg2 fileSize:(long long)arg3;
- (void)sendAllKindsFileWithURL:(id)arg1 fileName:(id)arg2;
- (void)sendMultiFilesWithURLs:(id)arg1 names:(id)arg2;
- (void)performKeyDown:(id)arg1;
- (BOOL)shouldMakeFirstResponder;
- (void)cellViewDidMouseCilckToStartVoipChatWithInviteType:(unsigned int)arg1;
- (void)onModifyContacts:(id)arg1;
- (void)onNetStatusChange:(int)arg1;
- (void)setupMultipleSelect;
- (void)updateChatComposeTextViewDelegate;
- (void)setupView;
- (void)CloseMultipleSelect:(id)arg1;
- (void)DeleteByMultipleSelect:(id)arg1;
- (void)AddFavoritesByMultipleSelect:(id)arg1;
- (void)ForwardByMergeMutipleSelect:(id)arg1;
- (void)ForwardByMultipleSelect:(id)arg1;
- (void)addLocalTipsMsg:(id)arg1;
- (void)showVoiceChat:(id)arg1;
- (void)showVideoChat:(id)arg1;
- (void)screenShotButtonPress:(id)arg1;
- (void)showAttachmentMenu:(id)arg1;
- (void)showStickerPicker:(id)arg1;
- (void)limitMultipleButtonContainerWidth:(double)arg1;
- (void)updateViewAndLayouts;
- (void)layoutForResize;
- (double)multipleSelectViewHeight;
- (BOOL)isMultipleSelectViewHidden;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

