//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor;

@interface MMRoundedRectangleView : NSView
{
    double m_cornerRadius;
    NSColor *m_backGroundColor;
}

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCornerRadius:(double)arg1 backgroundColor:(id)arg2 frameRect:(struct CGRect)arg3;

@end

